### ISSUE TITLE
chef_vm_extension fails if the machine name contains an index

### ISSUE THREAD

**Issue by pjjohnstone** [pendrica/chef-provisioning-azurerm#12]
When submitting a template with machine name:

`"name": "[concat(parameters('vmNamePrefix'), parameters('vmName'), copyindex())]",`

The deployment fails:

`    - adding a Chef VM Extension with name: [concat(parameters('vmNamePrefix'), copyindex())] and location: [resourceGroup().location] [2016-02-24T11:01:50+00
:00] ERROR: {"code"=>"InvalidTemplate", "message"=>"Deployment template validation failed: 'The template resource '[concat(concat(parameters('vmNamePrefix'),
copyindex()),'/', 'chefExtension')]' at line '1' and column '6930' is not valid: The template function 'copyIndex' is not expected at this location. The funct
ion can only be used in a resource with copy specified. Please see http://aka.ms/arm-copy for usage details..'."}`

Removing the index from the name works.

`"name": "[concat(parameters('vmNamePrefix'), parameters('vmName'))]",`

**Comment by stuartpreston** [comment]
@pjjohnstone Thanks for the report. Are you using copyIndex because you want to create multiple VMs using the same template. You can probably see the code is trying to use the concat function to append /chefExtension to the resource name but this fails if the name is also derived from an ARM expression of function.  I'll have another think about how to solve that one!

**Comment by pjjohnstone** [comment]
Yes, in this template I'm creating a number of vms in an availability set, behind a load balancer.  This seemed like the simplest way to have them share knowledge of the LB/AV sets and virtual network.

**Comment by chlsmith** [comment]
I want to put in a "vote" on this, too.   I'm spinning up multiple VMs and within the JSON template, I'm using copyIndex() there.   Installing the Chef extension afterward, though, fails because of the name not really being in the script.    

I've worked around this by just adding the extension into the JSON template and dropping it from the rb file.   It would be cool, though, if I could add the Chef extension this way.   :)

**Comment by stuartpreston** [comment]
I think it's a fair requirement, I'll have a think about it. All we're doing is substituting the existing value into this line in the template:

```
"name": "[concat(#{machine_name.delete('[]')},'/', 'chefExtension')]",
```

https://github.com/pendrica/chef-provisioning-azurerm/blob/master/lib/chef/provider/azure_resource_template.rb#L65

..so if you can think of an ARM compatible way of appending '/chefExtension' to the generated name that doesn't involve detecting and moving brackets then I'm all in :)

**Comment by stuartpreston** [comment]
I'm going to close this for now as wontfix - there's no way in an ARM template to create multiple resources from the same copy loop - so this is an exercise for the reader (with various of my customers we use an ARM template that is an ERB so that we can drive it from attributes).
